from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('profile/<int:user_id>/', views.view_profile, name='profile'),
    path('stores/', views.stores_index, name='index'),
    path('stores/<str:store_name>/detail/',
         views.stores_detail, name='detail'),
    path('logout/', views.logout, name='logout'),
    path('login/', views.login, name='login'),
    path('checkout/<int:user_id>/', views.checkout, name='checkout'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/signup/volunteer',
         views.volunteer_signup, name='volunteer_signup'),
    path('cart/<int:user_id>/', views.cart, name='cart'),
    path('customer/edit/',views.edit_profile, name="customer_update"),
    path('volunteer/edit/',views.edit_volunteer_profile, name="edit_volunteer_profile"),
    path('customer/password/',views.change_password, name="change_password"),
    path('volunteer/password/',views.change_volunteer_password, name="change_volunteer_password"),
    path('volunteer/<int:user_id>/add_photo/',
         views.add_photo, name="add_photo"),
    path('add_delivery_time/<int:user_id>/<int:volunteer_id>/',
         views.cart, name='add_timeslot'),
    path('cart/<int:user_id>/assoc_item/<int:item_id>/',
         views.assoc_item, name='assoc_item'),
    path('cart/<int:user_id>/disassoc_item/<int:item_id>/', views.disassoc_item, name='disassoc_item'),
    path('stores/<str:store_name>/detail/<int:user_id>/disassoc_item_in_store/<int:item_id>/', views.disassoc_item_in_store, name='disassoc_item_in_store'),
    path('checkout/delivery/<int:user_id>/',views.select_delivery, name="select_delivery"),
    path('checkout/delivery/<int:user_id>/<int:volunteer_id>/',views.add_delivery, name="add_delivery"),
]
