# Generated by Django 3.0.4 on 2020-04-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000, verbose_name='Image URL')),
            ],
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='availability_date',
            field=models.DateField(null=True, verbose_name='available date'),
        ),
    ]
