# Generated by Django 3.0.4 on 2020-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
