# Generated by Django 3.0.4 on 2020-04-16 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='customer',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Customer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='volunteer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.Volunteer'),
            preserve_default=False,
        ),
    ]
