# Generated by Django 3.0.4 on 2020-04-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200422_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='image',
            field=models.CharField(max_length=1000, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
