# Generated by Django 3.0.4 on 2020-04-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200424_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_ref',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
