# Generated by Django 3.0.4 on 2020-04-25 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_customer_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdelivery',
            name='date',
            field=models.DateField(default=datetime.date(2020, 4, 25), verbose_name='Delivery date'),
        ),
    ]
