# Generated by Django 3.0.4 on 2020-04-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_item_count_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count_ref',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
