# Generated by Django 3.0.4 on 2020-04-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200425_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdelivery',
            name='date',
            field=models.DateField(verbose_name='Delivery date'),
        ),
    ]
