# Generated by Django 3.0.4 on 2020-04-21 05:06

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200421_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_time',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', '9AM–10AM'), ('B', '10AM–11AM'), ('C', '11AM–12PM'), ('D', '12PM–1PM'), ('E', '1PM–2PM'), ('F', '2PM–3PM'), ('G', '3PM–4PM'), ('H', '4PM–5PM'), ('I', '5PM–6PM'), ('J', '6PM–7PM'), ('K', '7PM–8PM'), ('L', '8PM–9PM'), ('M', '9PM–10PM')], max_length=100, null=True),
        ),
    ]
